### ISSUE TITLE
Feature: decompile Kotlin's nested classes (companion objects, etc)

### ISSUE THREAD

**Issue by bric3** [marcelkliemannel/intellij-byte-code-plugin#27]
On a kotlin file, e.g.

```kotlin
class InlayHintsPassFactory  {
  fun regularMethod() {}

  companion object { <caret>
    fun companionMethod() {}
  }
}
```

It would be nice if the plugin could pick the companion and decompile it.

Actually Kotlin is creating a lot of nested classes, maybe the plugin could propose in a menu to open the nested classes.

```
❯ l modules/core/build/classes/kotlin/test/my/pkg/
Permissions Size User          Date Modified Name
.rw-r--r--@ 1.9k brice.dutheil 22 Sep 15:59  CodeInsightsInlayPresentationTest$Companion$testCodeInsightsInlay$collectorWithSettings$1.class
.rw-r--r--@ 6.1k brice.dutheil 22 Sep 15:59  CodeInsightsInlayPresentationTest$Companion.class
.rw-r--r--@ 1.8k brice.dutheil 22 Sep 15:59  CodeInsightsInlayPresentationTest$InlaysForLineBasedInsights$lineAnnotation$1.class
.rw-r--r--@ 6.9k brice.dutheil 22 Sep 15:59  CodeInsightsInlayPresentationTest$InlaysForLineBasedInsights.class
.rw-r--r--@ 4.7k brice.dutheil 22 Sep 15:59  CodeInsightsInlayPresentationTest$InlaysForPsiElementBasedInsights$should add single block inlay for multiple annotation of different kind$1.class
.rw-r--r--@ 4.4k brice.dutheil 22 Sep 15:59  CodeInsightsInlayPresentationTest$InlaysForPsiElementBasedInsights$should inject inlays at correct line$1.class
.rw-r--r--@ 4.5k brice.dutheil 22 Sep 15:59  CodeInsightsInlayPresentationTest$InlaysForPsiElementBasedInsights$should not inject inlays if no annotations$1.class
.rw-r--r--@ 4.7k brice.dutheil 22 Sep 15:59  CodeInsightsInlayPresentationTest$InlaysForPsiElementBasedInsights$should single block inlay and group multiple annotation of same kind$1.class
.rw-r--r--@ 1.9k brice.dutheil 22 Sep 15:59  CodeInsightsInlayPresentationTest$InlaysForPsiElementBasedInsights$symbolAnnotation$1.class
.rw-r--r--@ 7.6k brice.dutheil 22 Sep 15:59  CodeInsightsInlayPresentationTest$InlaysForPsiElementBasedInsights.class
.rw-r--r--@ 1.4k brice.dutheil 22 Sep 15:59  CodeInsightsInlayPresentationTest.class
```

**Comment by marcelkliemannel** [comment]
The next release will have a complete overhaul of the open class file mechanism to better support nested classes and Kotlin code.

Unfortunately, there is the limitation that the mechanism only works for classes where we can derive the class file name from the source code (or more precisely from the data model of it in IntelliJ). For anonymous classes and other special cases, it is up to the compiler to decide how to name them, so we cannot derive the class name from the source code for these.

However, the next release will have a drop-down menu that lists all the class files associated with the current view. This would also give quick access to the other classes mentioned:
<img width="238" alt="Screenshot 2023-12-17 at 20 13 33" src="https://github.com/marcelkliemannel/intellij-byte-code-plugin/assets/3964073/d2e9b62e-e332-4301-be01-dfbdf50b920a">

**Comment by bric3** [comment]
Cool thank you !

More generally do you think using the base class name as a prefix could work to identify nested / anonymous / local classes ?

**Comment by marcelkliemannel** [comment]
I took a closer look and found an easy way to get the class name of local/anonymous classes (the IntelliJ SDK has some built-in functionality for this). The next release should now have full support for these classes.
