### ISSUE TITLE
Support Kotlin K2 compiler

### ISSUE THREAD

**Issue by SettingDust** [marcelkliemannel/intellij-byte-code-plugin#41]

**Comment by marcelkliemannel** [comment]
The plugin only analyzes the compiled byte code, which should be independent of the compiler used. I also have no problems opening byte code created with the K2 compiler. What exactly is missing or not working?

**Comment by SettingDust** [comment]
Switch the IDE kotlin compiler to K2. The IDE says the plugin isn't supported

**Comment by marcelkliemannel** [comment]
Will be fixed with the next release 4.2.1
