### ISSUE TITLE
Show frames locals and stack wrong

### ISSUE THREAD

**Issue by Lenni0451** [marcelkliemannel/intellij-byte-code-plugin#9]
When viewing the frames of a method the columns stack and locals are swapped
![grafik](https://user-images.githubusercontent.com/20379977/127374028-35001078-6217-486f-a357-030026fa0653.png)

**Comment by marcelkliemannel** [comment]
Thanks for taking the time to create an issue. (Sorry for the long response time. I somehow overlooked the issue.)

In indeed, the two columns descriptions are swapped. It is fixed in version 2.0.3.
